import { ConfigurableFormSchema, SchemaOption } from '../models/form-schema';

function mapOptions(options: string[]): SchemaOption[] {
  return options.map((option) => ({
    label: option,
    value: option,
  }));
}

export const GENERIC_FORM_SCHEMA_2025: ConfigurableFormSchema = {
  schemaVersion: 'application-2025.1',
  formId: 'generic-configurable-form',
  name: 'Program Application',
  activeYears: [2025, 2026],
  context: {
    applicationYear: 2025,
    programCode: 'APPLICATION',
    applicantType: 'individual',
  },
  backendComputations: [],
  steps: [
    {
      id: 'application-questions',
      title: '2025 Application Questions',
      description: 'Adapted from the provided 2025 question set and mapped to the current schema contract.',
      route: 'application',
      applicableYears: [2025],
      questions: [
        {
          id: 'fullName',
          name: 'fullName',
          type: 'text',
          dataType: 'string',
          formControlName: 'fullName',
          databaseModel: 'applicantProfile',
          databaseProperty: 'fullName',
          label: 'Full Legal Name',
        },
        {
          id: 'email',
          name: 'email',
          type: 'email',
          dataType: 'string',
          formControlName: 'email',
          databaseModel: 'applicantProfile',
          databaseProperty: 'email',
          label: 'Email Address',
        },
        {
          id: 'phone',
          name: 'phone',
          type: 'text',
          dataType: 'string',
          formControlName: 'phone',
          databaseModel: 'applicantProfile',
          databaseProperty: 'phone',
          label: 'Phone Number',
        },
        {
          id: 'citizenshipStatus',
          name: 'citizenshipStatus',
          type: 'radio',
          dataType: 'string',
          formControlName: 'citizenshipStatus',
          databaseModel: 'applicantProfile',
          databaseProperty: 'citizenshipStatus',
          label: 'Are you a U.S. citizen?',
          options: mapOptions(['Yes', 'No']),
        },
        {
          id: 'state',
          name: 'state',
          type: 'select',
          dataType: 'string',
          formControlName: 'state',
          databaseModel: 'applicantProfile',
          databaseProperty: 'state',
          label: 'State of Residence',
          options: mapOptions(['NY', 'CA', 'TX', 'VA']),
        },
        {
          id: 'isStudent',
          name: 'isStudent',
          type: 'radio',
          dataType: 'string',
          formControlName: 'isStudent',
          databaseModel: 'educationProfile',
          databaseProperty: 'isStudent',
          label: 'Are you currently a student?',
          options: mapOptions(['Yes', 'No']),
        },
        {
          id: 'schoolName',
          name: 'schoolName',
          type: 'text',
          dataType: 'string',
          formControlName: 'schoolName',
          databaseModel: 'educationProfile',
          databaseProperty: 'schoolName',
          label: 'School Name',
          dependencies: [
            {
              effect: 'visible',
              when: 'all',
              conditions: [
                {
                  source: 'answer',
                  field: 'isStudent',
                  operator: 'equals',
                  value: 'Yes',
                },
              ],
            },
          ],
        },
        {
          id: 'fieldOfStudy',
          name: 'fieldOfStudy',
          type: 'text',
          dataType: 'string',
          formControlName: 'fieldOfStudy',
          databaseModel: 'educationProfile',
          databaseProperty: 'fieldOfStudy',
          label: 'Field of Study',
        },
        {
          id: 'whyApply',
          name: 'whyApply',
          type: 'textarea',
          dataType: 'string',
          formControlName: 'whyApply',
          databaseModel: 'applicationEssay',
          databaseProperty: 'whyApply',
          label: 'Why are you applying to this program?',
        },
        {
          id: 'heardAbout',
          name: 'heardAbout',
          type: 'multiCheckbox',
          dataType: 'stringArray',
          formControlName: 'heardAbout',
          databaseModel: 'applicationMeta',
          databaseProperty: 'heardAbout',
          label: 'How did you hear about this program?',
          options: mapOptions(['Friend', 'Social Media', 'School', 'Other']),
        },
      ],
    },
  ],
};

export const GENERIC_FORM_SCHEMA_2026: ConfigurableFormSchema = {
  schemaVersion: 'application-2026.1',
  formId: 'generic-configurable-form',
  name: 'Program Application',
  submissionUrl: '/api/forms/generic-configurable-form/years/2026/submissions',
  activeYears: [2025, 2026],
  context: {
    applicationYear: 2026,
    programCode: 'APPLICATION',
    applicantType: 'individual',
  },
  backendComputations: [],
  steps: [
    {
      id: 'application-questions',
      title: '2026 Application Questions',
      description: 'Adapted from the provided 2026 question set and mapped to the current schema contract.',
      route: 'application',
      applicableYears: [2026],
      questions: [
        {
          id: 'fullName',
          name: 'fullName',
          type: 'text',
          dataType: 'string',
          formControlName: 'fullName',
          databaseModel: 'applicantProfile',
          databaseProperty: 'fullName',
          label: 'Applicant Full Name',
        },
        {
          id: 'email',
          name: 'email',
          type: 'email',
          dataType: 'string',
          formControlName: 'email',
          databaseModel: 'applicantProfile',
          databaseProperty: 'email',
          label: 'Primary Email',
        },
        {
          id: 'state',
          name: 'state',
          type: 'select',
          dataType: 'string',
          formControlName: 'state',
          databaseModel: 'applicantProfile',
          databaseProperty: 'state',
          label: 'Which state do you currently live in?',
          options: mapOptions(['NY', 'CA', 'TX', 'VA', 'WA']),
        },
        {
          id: 'citizenshipStatus',
          name: 'citizenshipStatus',
          type: 'radio',
          dataType: 'string',
          formControlName: 'citizenshipStatus',
          databaseModel: 'applicantProfile',
          databaseProperty: 'citizenshipStatus',
          label: 'Citizenship Status',
          options: mapOptions(['U.S. Citizen', 'Permanent Resident', 'Other']),
        },
        {
          id: 'educationStatus',
          name: 'educationStatus',
          type: 'radio',
          dataType: 'string',
          formControlName: 'educationStatus',
          databaseModel: 'educationProfile',
          databaseProperty: 'educationStatus',
          label: 'What is your current education status?',
          options: mapOptions(['High School Student', 'College Student', 'Graduate', 'Not Currently Enrolled']),
        },
        {
          id: 'schoolName',
          name: 'schoolName',
          type: 'text',
          dataType: 'string',
          formControlName: 'schoolName',
          databaseModel: 'educationProfile',
          databaseProperty: 'schoolName',
          label: 'Current or Most Recent School',
        },
        {
          id: 'major',
          name: 'major',
          type: 'text',
          dataType: 'string',
          formControlName: 'major',
          databaseModel: 'educationProfile',
          databaseProperty: 'major',
          label: 'Major or Area of Study',
        },
        {
          id: 'goals',
          name: 'goals',
          type: 'textarea',
          dataType: 'string',
          formControlName: 'goals',
          databaseModel: 'applicationEssay',
          databaseProperty: 'goals',
          label: 'What are your academic or career goals?',
        },
        {
          id: 'whyApply',
          name: 'whyApply',
          type: 'textarea',
          dataType: 'string',
          formControlName: 'whyApply',
          databaseModel: 'applicationEssay',
          databaseProperty: 'whyApply',
          label: 'Tell us why you are interested in this program',
        },
        {
          id: 'previousParticipation',
          name: 'previousParticipation',
          type: 'radio',
          dataType: 'string',
          formControlName: 'previousParticipation',
          databaseModel: 'programHistory',
          databaseProperty: 'previousParticipation',
          label: 'Have you participated in this program before?',
          options: mapOptions(['Yes', 'No']),
        },
        {
          id: 'referralSource',
          name: 'referralSource',
          type: 'select',
          dataType: 'string',
          formControlName: 'referralSource',
          databaseModel: 'applicationMeta',
          databaseProperty: 'referralSource',
          label: 'How did you learn about us?',
          options: mapOptions(['Friend', 'Teacher', 'Online Search', 'Social Media', 'Other']),
        },
      ],
    },
  ],
};

export const GENERIC_FORM_SCHEMAS_BY_YEAR: Record<number, ConfigurableFormSchema> = {
  2025: GENERIC_FORM_SCHEMA_2025,
  2026: GENERIC_FORM_SCHEMA_2026,
};

export const GENERIC_FORM_SCHEMA = GENERIC_FORM_SCHEMA_2026;
