import { ConfigurableFormSchema } from '../models/form-schema';

export const GENERIC_FORM_SCHEMA: ConfigurableFormSchema = {
  schemaVersion: '2026-03-18',
  formId: 'generic-configurable-form',
  name: 'Generic Configurable Form',
  activeYears: [2025, 2026, 2027],
  context: {
    applicationYear: 2026,
    programCode: 'GENERIC',
    applicantType: 'individual',
  },
  backendComputations: [
    {
      key: 'lookupResult',
      description: 'Generic backend lookup that can return derived values used by step or question rules.',
      endpoint: '/api/forms/:formId/lookup-result',
      method: 'POST',
      requestTemplate: {
        includeAnswers: ['textValue', 'numericValue', 'selectedOption'],
        includeContext: ['applicationYear'],
      },
    },
  ],
  steps: [
    {
      id: 'basic-data',
      title: 'Basic data',
      description: 'Questions in this step show the expected answer type for each field.',
      route: 'basic-data',
      applicableYears: [2025, 2026, 2027],
      questions: [
        {
          id: 'applicationYear',
          name: 'applicationYear',
          type: 'radio',
          dataType: 'string',
          formControlName: 'applicationYear',
          databaseModel: 'application',
          databaseProperty: 'year',
          label: 'Application year',
          helpText: 'Single selected value represented as a string.',
          defaultValue: '2026',
          options: [
            { label: '2025', value: '2025' },
            { label: '2026', value: '2026' },
            { label: '2027', value: '2027' },
          ],
          validations: [
            {
              type: 'required',
              message: 'A year is required.',
            },
          ],
        },
        {
          id: 'textValue',
          name: 'textValue',
          type: 'text',
          dataType: 'string',
          formControlName: 'textValue',
          databaseModel: 'basicData',
          databaseProperty: 'textValue',
          label: 'Text value',
          helpText: 'Free-form text stored as a string.',
          placeholder: 'Enter any string value',
          validations: [
            {
              type: 'required',
              message: 'A text value is required.',
            },
          ],
        },
        {
          id: 'numericValue',
          name: 'numericValue',
          type: 'number',
          dataType: 'number',
          formControlName: 'numericValue',
          databaseModel: 'basicData',
          databaseProperty: 'numericValue',
          label: 'Numeric value',
          helpText: 'Whole or decimal number stored as a number.',
          validations: [
            {
              type: 'min',
              value: 0,
              message: 'Numeric value must be zero or greater.',
            },
          ],
        },
        {
          id: 'dateValue',
          name: 'dateValue',
          type: 'date',
          dataType: 'date',
          formControlName: 'dateValue',
          databaseModel: 'basicData',
          databaseProperty: 'dateValue',
          label: 'Date value',
          helpText: 'Calendar date stored as a date string or normalized backend date format.',
        },
        {
          id: 'booleanValue',
          name: 'booleanValue',
          type: 'yesNo',
          dataType: 'boolean',
          formControlName: 'booleanValue',
          databaseModel: 'basicData',
          databaseProperty: 'booleanValue',
          label: 'Boolean value',
          helpText: 'Yes or no answer stored as true or false.',
          validations: [
            {
              type: 'required',
              message: 'A yes or no answer is required.',
            },
          ],
        },
      ],
    },
    {
      id: 'selection-data',
      title: 'Selection data',
      description: 'Examples of questions whose answer comes from predefined options.',
      route: 'selection-data',
      questions: [
        {
          id: 'selectedOption',
          name: 'selectedOption',
          type: 'select',
          dataType: 'string',
          formControlName: 'selectedOption',
          databaseModel: 'selectionData',
          databaseProperty: 'selectedOption',
          label: 'Single select value',
          helpText: 'One selected option stored as a string.',
          options: [
            { label: 'Option A', value: 'option-a' },
            { label: 'Option B', value: 'option-b' },
            { label: 'Option C', value: 'option-c' },
          ],
        },
        {
          id: 'selectedRadio',
          name: 'selectedRadio',
          type: 'radio',
          dataType: 'string',
          formControlName: 'selectedRadio',
          databaseModel: 'selectionData',
          databaseProperty: 'selectedRadio',
          label: 'Radio value',
          helpText: 'One selected option stored as a string.',
          options: [
            { label: 'Choice 1', value: 'choice-1' },
            { label: 'Choice 2', value: 'choice-2' },
          ],
        },
        {
          id: 'selectedFlags',
          name: 'selectedFlags',
          type: 'multiCheckbox',
          dataType: 'stringArray',
          formControlName: 'selectedFlags',
          databaseModel: 'selectionData',
          databaseProperty: 'selectedFlags',
          label: 'Multiple checkbox values',
          helpText: 'Multiple selected options stored as an array of strings.',
          options: [
            { label: 'Flag A', value: 'flag-a' },
            { label: 'Flag B', value: 'flag-b' },
            { label: 'Flag C', value: 'flag-c' },
          ],
        },
        {
          id: 'consentAccepted',
          name: 'consentAccepted',
          type: 'checkbox',
          dataType: 'boolean',
          formControlName: 'consentAccepted',
          databaseModel: 'selectionData',
          databaseProperty: 'consentAccepted',
          label: 'Consent checkbox',
          helpText: 'Single checkbox stored as true or false.',
        },
      ],
    },
    {
      id: 'conditional-data',
      title: 'Conditional data',
      description: 'Generic examples of answer-based and backend-based dependencies.',
      route: 'conditional-data',
      questions: [
        {
          id: 'detailsText',
          name: 'detailsText',
          type: 'textarea',
          dataType: 'string',
          formControlName: 'detailsText',
          databaseModel: 'conditionalData',
          databaseProperty: 'detailsText',
          label: 'Details text',
          helpText: 'Long-form text stored as a string.',
          dependencies: [
            {
              effect: 'visible',
              when: 'all',
              conditions: [
                {
                  source: 'answer',
                  field: 'booleanValue',
                  operator: 'equals',
                  value: true,
                },
              ],
            },
          ],
        },
        {
          id: 'derivedStatus',
          name: 'derivedStatus',
          type: 'radio',
          dataType: 'string',
          formControlName: 'derivedStatus',
          databaseModel: 'conditionalData',
          databaseProperty: 'derivedStatus',
          label: 'Derived backend status',
          helpText: 'Visible only when a backend result exists.',
          options: [
            { label: 'Pass', value: 'pass' },
            { label: 'Review', value: 'review' },
            { label: 'Fail', value: 'fail' },
          ],
          backendDependencies: [
            {
              key: 'lookupResult',
              description: 'Requires a backend lookup result before this question is shown.',
              resultPath: 'status',
              required: true,
            },
          ],
          dependencies: [
            {
              effect: 'visible',
              when: 'all',
              conditions: [
                {
                  source: 'backend',
                  backendKey: 'lookupResult.status',
                  operator: 'exists',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
